### ISSUE TITLE
Documentation: 32Mb Flash needed?

### ISSUE THREAD

**Issue by Testi89** [lechiJb/myRadio#1]
This is not a bug, but more a documentation request.

Please add a remark about the flash size of the needed chip. I have tested it with ESP12 with 4Mb (512kB) chip and it is not working.

Thanks a lot and good job!

**Comment by lechiJb** [comment]
Hey!

Thanky you for your comment. I will update the documentation. At the moment I tested the code at a ESP12e and a ESP12f. 
The audio-streaming itself works also at a ESP12, but I never tried to run the whole project (including server, etc...). So I will update the documentation.
